[tool.ruff]
extend-exclude = ["cmake"]

[tool.ruff.lint]
extend-ignore = ["COM812", "D203", "D213"]
extend-select = ["A", "B", "C", "COM", "EM", "EXE", "G", "NPY", "PTH", "RET", "RUF", "UP", "W", "YTT"]

[tool.tomlsort]
all = true
